# Пример для проекта на Node.js
name: setup_test_lint
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      # Ставим зависимости
      - run: make install
      # Установка и запуск проекта
      - setup: make setup
        start: make start # setup и start относятся к одной задаче, поэтому дефис ставится только перед setup
      # Запускаем тесты
      - run tests: make test
      # Запускаем линтер
      - run linter: make lint
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
