# Пример для проекта на Node.js
name: setup_test_lint
on: push
jobs:
  first_workflow: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
#      # Клонируем репозиторий
#      - uses: actions/checkout@v3
#      # Устанавливаем Node.js
#      - uses: actions/setup-node@v3
#      # Ставим зависимости
#      - run: npm install
      # Установка проекта
#      - run: make setup
      # Запуск проекта
      - run: make start
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
      # Запускаем линтер
      - run: make lint

